import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "zh";

const LANGUAGE_STORAGE_KEY = "paperclip.language";

type TranslationValues = Record<string, string | number>;

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  toggleLanguage: () => void;
  t: (keyOrZh: string, valuesOrEn?: TranslationValues | string, inlineValues?: TranslationValues) => string;
};

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    "agent.action.approve": "Approve agent",
    "agent.action.assignTask": "Assign Task",
    "agent.action.copyId": "Copy Agent ID",
    "agent.action.create": "Create agent",
    "agent.action.creating": "Creating...",
    "agent.action.new": "New Agent",
    "agent.action.pause": "Pause",
    "agent.action.resetSessions": "Reset Sessions",
    "agent.action.resume": "Resume",
    "agent.action.runHeartbeat": "Run Heartbeat",
    "agent.action.runNow": "Run now",
    "agent.action.terminate": "Terminate",
    "agent.action.test": "Test Agent",
    "agent.action.testing": "Testing...",
    "agent.breadcrumb.agent": "Agent",
    "agent.breadcrumb.agents": "Agents",
    "agent.breadcrumb.budget": "Budget",
    "agent.breadcrumb.configuration": "Configuration",
    "agent.breadcrumb.dashboard": "Dashboard",
    "agent.breadcrumb.instructions": "Instructions",
    "agent.breadcrumb.run": "Run {id}",
    "agent.breadcrumb.runs": "Runs",
    "agent.breadcrumb.skills": "Skills",
    "agent.config.adapter": "Adapter",
    "agent.config.adapterType": "Adapter type",
    "agent.config.advancedRunPolicy": "Advanced Run Policy",
    "agent.config.bootstrapPrompt": "Bootstrap prompt (legacy)",
    "agent.config.capabilities": "Capabilities",
    "agent.config.cheapModel": "Cheap model",
    "agent.config.cheapModelDescription": "Used when a run requests the cheap profile (e.g. routine summaries). The primary model stays unchanged.",
    "agent.config.cheapModelNoDefault": "No cheap model selected and the adapter has no default. Cheap-lane runs will continue on the primary model with a fallback note.",
    "agent.config.cheapModelPlaceholder": "No adapter default — choose a cheaper model",
    "agent.config.cheapModelUsesDefault": "No explicit cheap model selected — runtime falls back to {model}.",
    "agent.config.command": "Command",
    "agent.config.capabilitiesPlaceholder": "Describe what this agent can do...",
    "agent.config.companyDefaultLocal": "Company default (Local)",
    "agent.config.continuationAttempts": "Continuation attempts",
    "agent.config.continuationDelay": "Continuation delay (sec)",
    "agent.config.continueAfterMaxTurn": "Continue after max-turn stop",
    "agent.config.cooldown": "Cooldown (sec)",
    "agent.config.defaultEnvironment": "Default environment",
    "agent.config.defaultEnvironmentHint": "Agent-level default execution target. Project and issue settings can still override this.",
    "agent.config.environmentVariables": "Environment variables",
    "agent.config.environmentTestFailed": "Environment test failed",
    "agent.config.execution": "Execution",
    "agent.config.extraArgs": "Extra args (comma-separated)",
    "agent.config.extraArgsPlaceholder": "e.g. --verbose, --foo=bar",
    "agent.config.heartbeatInterval": "Heartbeat on interval",
    "agent.config.identity": "Identity",
    "agent.config.interruptGrace": "Interrupt grace period (sec)",
    "agent.config.maxConcurrentRuns": "Max concurrent runs",
    "agent.config.name": "Name",
    "agent.config.permissions": "Permissions",
    "agent.config.permissionsAndConfiguration": "Permissions & Configuration",
    "agent.config.primaryModel": "Primary model",
    "agent.config.promptTemplate": "Prompt Template",
    "agent.config.promptTemplatePlaceholder": "You are agent {{ agent.name }}. Your role is {{ agent.role }}...",
    "agent.config.promptTemplateWarning": "Prompt template is replayed on every heartbeat. Keep it compact and dynamic to avoid recurring token cost and cache churn.",
    "agent.config.runEveryPrefix": "Run heartbeat every",
    "agent.config.runEverySuffix": "sec",
    "agent.config.runPolicy": "Run Policy",
    "agent.config.save": "Save",
    "agent.config.saving": "Saving...",
    "agent.config.bootstrapPromptPlaceholder": "Optional initial setup prompt for the first run",
    "agent.config.bootstrapPromptWarning": "Bootstrap prompt is legacy and will be removed in a future release. Consider moving this content into the agent's prompt template or instructions file instead.",
    "agent.config.cheapModelUsesDefaultPrefix": "No explicit cheap model selected — runtime falls back to",
    "agent.config.test": "Test",
    "agent.config.thinkingEffort": "Thinking effort",
    "agent.config.timeout": "Timeout (sec)",
    "agent.config.title": "Title",
    "agent.config.titlePlaceholder": "e.g. VP of Engineering",
    "agent.config.model": "Model",
    "agent.config.unsavedChanges": "Unsaved changes",
    "agent.config.wakeOnDemand": "Wake on demand",
    "agent.config.workingDirectoryDeprecated": "Working directory (deprecated)",
    "agent.detail.apiKeys": "API Keys",
    "agent.detail.approvalPending": "This agent is pending board approval and cannot be invoked yet.",
    "agent.detail.cachedTokens": "Cached tokens",
    "agent.detail.canAssignTasks": "Can assign tasks",
    "agent.detail.canCreateAgents": "Can create new agents",
    "agent.detail.configRevisions": "Configuration Revisions",
    "agent.detail.cost": "Cost",
    "agent.detail.costs": "Costs",
    "agent.detail.date": "Date",
    "agent.detail.input": "Input",
    "agent.detail.inputTokens": "Input tokens",
    "agent.detail.moreIssues": "+{count} more issues",
    "agent.detail.noConfigRevisions": "No configuration revisions yet.",
    "agent.detail.noTrackedChanges": "no tracked changes",
    "agent.detail.noRecentIssues": "No recent issues.",
    "agent.detail.output": "Output",
    "agent.detail.outputTokens": "Output tokens",
    "agent.detail.permissionsDescription": "Lets this agent create or hire agents and implicitly assign tasks.",
    "agent.detail.recentIssues": "Recent Issues",
    "agent.detail.run": "Run",
    "agent.detail.runActivity": "Run Activity",
    "agent.detail.seeAll": "See All →",
    "agent.detail.successRate": "Success Rate",
    "agent.detail.taskAssign.ceoRole": "Enabled automatically for CEO agents.",
    "agent.detail.taskAssign.creator": "Enabled automatically while this agent can create new agents.",
    "agent.detail.taskAssign.disabled": "Disabled unless explicitly granted.",
    "agent.detail.taskAssign.explicit": "Enabled via explicit company permission grant.",
    "agent.detail.totalCost": "Total cost",
    "agent.detail.byPriority": "Issues by Priority",
    "agent.detail.byStatus": "Issues by Status",
    "agent.instructions.advanced": "Advanced",
    "agent.instructions.availableLocalOnly": "Instructions bundles are only available for local adapters.",
    "agent.instructions.copyMarkdown": "Copy as markdown",
    "agent.instructions.create": "Create",
    "agent.instructions.delete": "Delete",
    "agent.instructions.deleteConfirm": "Delete {file}?",
    "agent.instructions.deprecatedVirtualFile": "Deprecated virtual file",
    "agent.instructions.entryFile": "Entry file",
    "agent.instructions.entryFileHint": "The main file the agent reads first when loading instructions. Defaults to AGENTS.md.",
    "agent.instructions.external": "External",
    "agent.instructions.fileContents": "File contents",
    "agent.instructions.files": "Files",
    "agent.instructions.fileType": "{language} file",
    "agent.instructions.managed": "Managed",
    "agent.instructions.managedPath": "(managed)",
    "agent.instructions.mode": "Mode",
    "agent.instructions.modeHint": "Managed: Paperclip stores and serves the instructions bundle. External: you provide a path on disk where the instructions live.",
    "agent.instructions.newFileInBundle": "New file in this bundle",
    "agent.instructions.placeholder": "# Agent instructions",
    "agent.instructions.rootPath": "Root path",
    "agent.instructions.rootPathHint": "The absolute directory on disk where the instructions bundle lives. In managed mode this is set by Paperclip automatically.",
    "agent.instructions.virtualFile": "virtual file",
    "agent.instructions.virtualFileHint": "Legacy inline prompt — this deprecated virtual file preserves the old promptTemplate content",
    "agent.error.couldNotSave": "Could not save agent",
    "agent.error.openCodeExplicitModel": "OpenCode requires an explicit model in provider/model format.",
    "agent.error.noAgentReference": "No agent reference",
    "agent.error.resetSessionFailed": "Failed to reset sessions",
    "agent.error.saveFailed": "Save failed",
    "agent.error.actionFailed": "Action failed",
    "agent.error.selectCompanyCreateSecrets": "Select a company to create secrets",
    "agent.error.selectCompanyDetectModel": "Select a company to detect the model",
    "agent.error.selectCompanyTestEnvironment": "Select a company to test adapter environment",
    "agent.error.selectCompanyUploadImages": "Select a company to upload images",
    "agent.error.updatePermissionsFailed": "Failed to update permissions",
    "agent.keys.active": "Active Keys",
    "agent.keys.banner": "API key created — copy it now, it will not be shown again.",
    "agent.keys.create": "Create API Key",
    "agent.keys.defaultName": "Default",
    "agent.keys.description": "API keys allow this agent to authenticate calls to the Paperclip server.",
    "agent.keys.dismiss": "Dismiss",
    "agent.keys.hide": "Hide",
    "agent.keys.copied": "Copied!",
    "agent.keys.created": "Created",
    "agent.keys.loading": "Loading keys...",
    "agent.keys.namePlaceholder": "Key name (e.g. production)",
    "agent.keys.noActive": "No active API keys.",
    "agent.keys.revoked": "Revoked Keys",
    "agent.keys.revokedAt": "Revoked",
    "agent.keys.revoke": "Revoke",
    "agent.keys.show": "Show",
    "agent.run.adapter": "Adapter:",
    "agent.run.after": "After",
    "agent.run.assignment": "Assignment",
    "agent.run.automation": "Automation",
    "agent.run.backToRuns": "Back to runs",
    "agent.run.baseRef": "Base ref:",
    "agent.run.before": "Before",
    "agent.run.branch": "Branch:",
    "agent.run.cached": "Cached",
    "agent.run.cancel": "Cancel",
    "agent.run.cancelling": "Cancelling...",
    "agent.run.clearSession": "clear session for these issues",
    "agent.run.clearSessionConfirm": "Clear session for {count} issue{plural} touched by this run?",
    "agent.run.clearingSession": "clearing session...",
    "agent.run.cleanup": "Cleanup:",
    "agent.run.command": "Command:",
    "agent.run.commandNotes": "Command notes",
    "agent.run.context": "Context",
    "agent.run.cost": "Cost",
    "agent.run.createdByRun": "Created by this run",
    "agent.run.details": "Details",
    "agent.run.duration": "Duration:",
    "agent.run.environment": "Environment",
    "agent.run.error": "Error:",
    "agent.run.events": "Events ({count})",
    "agent.run.exitCode": "Exit code {code}",
    "agent.run.failureDetails": "Failure details",
    "agent.run.failedClearSessions": "Failed to clear sessions",
    "agent.run.failedLoadLog": "Failed to load run log",
    "agent.run.failedLoadMoreLog": "Failed to load more run log",
    "agent.run.failedLoadWorkspaceLog": "Failed to load workspace operation log",
    "agent.run.failedResume": "Failed to resume run",
    "agent.run.failedRetry": "Failed to retry run",
    "agent.run.failedClaudeLogin": "Failed to run Claude login",
    "agent.run.hideFullLog": "Hide full log",
    "agent.run.input": "Input",
    "agent.run.invocation": "Invocation",
    "agent.run.issuesTouched": "Issues Touched ({count})",
    "agent.run.jumpToLive": "Jump to live",
    "agent.run.latestRun": "Latest Run",
    "agent.run.live": "Live",
    "agent.run.liveRun": "Live Run",
    "agent.run.loadMoreLog": "Load more log",
    "agent.run.loading": "Loading...",
    "agent.run.loadingLog": "Loading log...",
    "agent.run.loadingRunLogs": "Loading run logs...",
    "agent.run.loginToClaude": "Login to Claude Code",
    "agent.run.loginUrl": "Login URL:",
    "agent.run.noLogEvents": "No log events.",
    "agent.run.noPersistedLogLines": "No persisted log lines.",
    "agent.run.noPersistedTranscript": "No persisted transcript for this run.",
    "agent.run.noRuns": "No runs yet.",
    "agent.run.onDemand": "On-demand",
    "agent.run.output": "Output",
    "agent.run.prompt": "Prompt",
    "agent.run.repoRoot": "Repo root:",
    "agent.run.resume": "Resume",
    "agent.run.resumeSkipped": "Resume request was skipped.",
    "agent.run.resuming": "Resuming...",
    "agent.run.retry": "Retry",
    "agent.run.retrySkipped": "Retry was skipped.",
    "agent.run.retrying": "Retrying...",
    "agent.run.reusedWorkspace": "Reused existing workspace",
    "agent.run.session": "Session",
    "agent.run.sessionChanged": "(changed)",
    "agent.run.showFullLog": "Show full log",
    "agent.run.signal": "(signal: {signal})",
    "agent.run.showingLogBytes": "Showing the first {shown} KB",
    "agent.run.showingLogBytesOf": "Showing the first {shown} KB of {total} KB",
    "agent.run.stderrExcerpt": "stderr excerpt",
    "agent.run.stdoutExcerpt": "stdout excerpt",
    "agent.run.timer": "Timer",
    "agent.run.transcript": "Transcript ({count})",
    "agent.run.waitingTranscript": "Waiting for transcript...",
    "agent.run.workingDir": "Working dir:",
    "agent.run.workspace": "Workspace ({count})",
    "agent.run.worktree": "Worktree:",
    "agent.run.phase.worktree_prepare": "Worktree setup",
    "agent.run.phase.workspace_provision": "Provision",
    "agent.run.phase.workspace_teardown": "Teardown",
    "agent.run.phase.worktree_cleanup": "Worktree cleanup",
    "agent.skills.adapter": "Adapter",
    "agent.skills.applied": "Skills applied",
    "agent.skills.appliedEphemeral": "Applied when the agent runs",
    "agent.skills.appliedPersistent": "Kept in the workspace",
    "agent.skills.appliedTrackedOnly": "Tracked only",
    "agent.skills.appliedUnknown": "Unknown",
    "agent.skills.companyLibrary": "View company skills library",
    "agent.skills.importFirst": "Import skills into the company library first, then attach them here.",
    "agent.skills.location": "Location:",
    "agent.skills.manageInAdapter": "Manage skills in the adapter directly.",
    "agent.skills.missing": "Requested skills missing from the company library",
    "agent.skills.required": "Required by Paperclip",
    "agent.skills.savingChanges": "Saving changes...",
    "agent.skills.savingSoon": "Saving soon...",
    "agent.skills.selected": "Selected skills",
    "agent.skills.unsupportedAcp": "Paperclip cannot manage skills for custom ACP commands yet.",
    "agent.skills.unsupportedAdapter": "Paperclip cannot manage skills for this adapter yet. Manage them in the adapter directly.",
    "agent.skills.unsupportedOpenClaw": "Paperclip cannot manage OpenClaw skills here. Visit your OpenClaw instance to manage this agent's skills.",
    "agent.skills.updateFailed": "Failed to update skills",
    "agent.skills.unmanaged": "({count}) User-installed skills, not managed by Paperclip",
    "agent.skills.view": "View",
    "agent.form.companySkills": "Company skills",
    "agent.form.companySkillsDescription": "Optional skills from the company library. Built-in Paperclip runtime skills are added automatically.",
    "agent.form.createFailed": "Failed to create agent",
    "agent.form.firstAgentCeo": "This will be the CEO",
    "agent.form.noOptionalSkills": "No optional company skills installed yet.",
    "agent.form.subtitle": "Advanced agent configuration",
    "agent.form.titlePlaceholder": "Title (e.g. VP of Engineering)",
    "agent.help.adapterType": "How this agent runs: local CLI (Claude/Codex/OpenCode), OpenClaw Gateway, spawned process, or generic HTTP webhook.",
    "agent.help.bootstrapPrompt": "Only sent when Paperclip starts a fresh session. Use this for stable setup guidance that should not be repeated on every heartbeat.",
    "agent.help.capabilities": "Describes what this agent can do. Shown in the org chart and used for task routing.",
    "agent.help.cooldownSec": "Minimum seconds between consecutive heartbeat runs.",
    "agent.help.cwd": "Deprecated legacy working directory fallback for local adapters. Existing agents may still carry this value, but new configurations should use project workspaces instead.",
    "agent.help.envVars": "Environment variables injected into the adapter process. Use plain values or secret references.",
    "agent.help.extraArgs": "Extra CLI arguments for local adapters, comma-separated.",
    "agent.help.graceSec": "Seconds to wait after sending interrupt before force-killing the process.",
    "agent.help.heartbeatInterval": "Run this agent automatically on a timer. Useful for periodic tasks like checking for new work.",
    "agent.help.intervalSec": "Seconds between automatic heartbeat invocations.",
    "agent.help.localCommand": "Override the path to the CLI command you want the adapter to call (e.g. /usr/local/bin/claude, codex, opencode).",
    "agent.help.maxConcurrentRuns": "Maximum number of heartbeat runs that can execute simultaneously for this agent.",
    "agent.help.maxTurnContinuationDelaySec": "Seconds to wait before starting each max-turn continuation.",
    "agent.help.maxTurnContinuationEnabled": "Automatically queue bounded continuation runs when an adapter stops because its per-run turn cap was exhausted.",
    "agent.help.maxTurnContinuationMaxAttempts": "Maximum automatic continuations after one max-turn stop. This is separate from max turns per run.",
    "agent.help.model": "Override the default model used by the adapter.",
    "agent.help.name": "Display name for this agent.",
    "agent.help.promptTemplate": "Sent on every heartbeat. Keep this small and dynamic. Use it for current-task framing, not large static instructions. Supports {{ agent.id }}, {{ agent.name }}, {{ agent.role }} and other template variables.",
    "agent.help.reportsTo": "The agent this one reports to in the org hierarchy.",
    "agent.help.thinkingEffort": "Control model reasoning depth. Supported values vary by adapter/model.",
    "agent.help.timeoutSec": "Maximum seconds a run can take before being terminated. 0 means no timeout.",
    "agent.help.title": "Job title shown in the org chart.",
    "agent.help.wakeOnDemand": "Allow this agent to be woken by assignments, API calls, UI actions, or automated systems.",
    "agent.list.count": "{count} agent{plural}",
    "agent.list.empty": "Create your first agent to get started.",
    "agent.list.filter.active": "Active",
    "agent.list.filter.all": "All",
    "agent.list.filter.error": "Error",
    "agent.list.filter.paused": "Paused",
    "agent.list.filters": "Filters",
    "agent.list.live": "Live{count}",
    "agent.list.noFilterMatch": "No agents match the selected filter.",
    "agent.list.noOrg": "No organizational hierarchy defined.",
    "agent.list.selectCompany": "Select a company to view agents.",
    "agent.list.showTerminated": "Show terminated",
    "agent.model.default": "Default",
    "agent.model.detect": "Detect model",
    "agent.model.detectFromConfig": "Detect from config",
    "agent.model.detected": "detected",
    "agent.model.detecting": "Detecting...",
    "agent.model.empty": "No models found.",
    "agent.model.emptyDetect": "No model detected. Select or enter one manually.",
    "agent.model.emptyDetectManual": "No model detected yet. Enter a provider/model manually.",
    "agent.model.current": "current",
    "agent.model.loadFailed": "Failed to load adapter models.",
    "agent.model.manual": "Use manual model",
    "agent.model.openCodeLocalOnly": "Live OpenCode model discovery only runs for Local environments. Using the curated list and manual entry for {environment}.",
    "agent.model.redetect": "Re-detect from config",
    "agent.model.refresh": "Refresh models",
    "agent.model.refreshFailed": "Failed to refresh adapter models.",
    "agent.model.refreshing": "Refreshing...",
    "agent.model.search": "Search models...",
    "agent.model.searchCreate": "Search models... (type to create)",
    "agent.model.select": "Select model",
    "agent.model.selectRequired": "Select model (required)",
    "agent.properties.adapter": "Adapter",
    "agent.properties.created": "Created",
    "agent.properties.lastError": "Last error",
    "agent.properties.lastHeartbeat": "Last Heartbeat",
    "agent.properties.reportsTo": "Reports To",
    "agent.properties.role": "Role",
    "agent.properties.session": "Session",
    "agent.properties.status": "Status",
    "agent.properties.title": "Title",
    "agent.reports.choose": "Reports to...",
    "agent.reports.chooseManager": "Choose manager...",
    "agent.reports.currentTerminated": "Current: {name} (terminated)",
    "agent.reports.disabledCeo": "Reports to: N/A (CEO)",
    "agent.reports.manager": "Reports to {name}{suffix}",
    "agent.reports.missing": "Saved manager is missing from this company. Choose a new manager or clear.",
    "agent.reports.noManager": "No manager",
    "agent.reports.terminatedSuffix": " (terminated)",
    "agent.reports.unknown": "Unknown manager (stale ID)",
    "agent.role.designer": "Designer",
    "agent.role.devops": "DevOps",
    "agent.role.engineer": "Engineer",
    "agent.role.general": "General",
    "agent.role.pm": "PM",
    "agent.role.qa": "QA",
    "agent.role.researcher": "Researcher",
    "agent.role.security": "Security",
    "account.board": "Board",
    "account.signedIn": "Signed in",
    "account.localBoard": "Local workspace board",
    "account.badge.authenticated": "Account",
    "account.badge.local": "Local",
    "account.openMenu": "Open account menu",
    "account.viewProfile": "View profile",
    "account.viewProfileDescription": "View your activity, tasks, and usage history.",
    "account.editProfile": "Edit profile",
    "account.editProfileDescription": "Update display name and avatar.",
    "account.instanceSettings": "Instance settings",
    "account.instanceSettingsDescription": "Return to the last opened settings page.",
    "account.docs": "Docs",
    "account.docsDescription": "Open Paperclip docs in a new tab.",
    "account.language": "Language",
    "account.languageDescription": "Switch between English and Chinese.",
    "account.themeLight": "Switch to light mode",
    "account.themeDark": "Switch to dark mode",
    "account.themeDescription": "Switch the app appearance.",
    "account.signingOut": "Signing out...",
    "account.signOut": "Sign out",
    "account.signOutDescription": "End the current browser session.",
    "project.status.backlog": "Backlog",
    "project.status.planned": "Planned",
    "project.status.in_progress": "In Progress",
    "project.status.completed": "Completed",
    "project.status.cancelled": "Cancelled",
    "project.fallback": "Project",
    "project.breadcrumb": "Projects",
    "project.description.placeholder": "Add a description...",
    "project.field.status": "Status",
    "project.field.targetDate": "Target Date",
    "project.color.change": "Change project color",
    "project.color.select": "Select color {color}",
    "project.toast.archived": "\"{name}\" has been archived",
    "project.toast.unarchived": "\"{name}\" has been unarchived",
    "project.toast.archiveFailed": "Failed to archive project",
    "project.toast.unarchiveFailed": "Failed to unarchive project",
    "project.error.noCompany": "No company selected",
    "project.pausedByBudget": "Paused by budget hard stop",
    "project.managedBy": "Managed by {name}",
    "project.tab.issues": "Issues",
    "project.tab.overview": "Overview",
    "project.tab.pluginOperations": "Plugin operations",
    "project.tab.workspaces": "Workspaces",
    "project.tab.configuration": "Configuration",
    "project.tab.budget": "Budget",
    "project.loadingWorkspaces": "Loading workspaces...",
    "projectDialog.localFolderName": "Local folder",
    "projectDialog.githubRepoName": "GitHub repo",
    "projectDialog.error.localFolderAbsolute": "Local folder must be a full absolute path.",
    "projectDialog.error.repoUrl": "Repo must use a valid GitHub or GitHub Enterprise repo URL.",
    "projectDialog.title": "New project",
    "projectDialog.namePlaceholder": "Project name",
    "projectDialog.descriptionPlaceholder": "Add description...",
    "projectDialog.repoUrl": "Repo URL",
    "projectDialog.optional": "optional",
    "projectDialog.repoHelp": "Link a GitHub repository so agents can clone, read, and push code for this project.",
    "projectDialog.localFolder": "Local folder",
    "projectDialog.localFolderHelp": "Set an absolute path on this machine where local agents will read and write files for this project.",
    "projectDialog.removeGoal": "Remove goal {title}",
    "projectDialog.addGoal": "+ Goal",
    "projectDialog.goal": "Goal",
    "projectDialog.noGoal": "No goal",
    "projectDialog.allGoalsSelected": "All goals already selected.",
    "projectDialog.targetDate": "Target date",
    "projectDialog.createFailed": "Failed to create project.",
    "projectDialog.creating": "Creating...",
    "projectDialog.create": "Create project",
    "projectProps.saving": "Saving",
    "projectProps.saved": "Saved",
    "projectProps.failed": "Failed",
    "projectProps.archive": "Archive",
    "projectProps.unarchive": "Unarchive",
    "projectProps.archiveDescription": "Archive this project to hide it from the sidebar and project selectors.",
    "projectProps.unarchiveDescription": "Unarchive this project to restore it in the sidebar and project selectors.",
    "projectProps.archiving": "Archiving...",
    "projectProps.unarchiving": "Unarchiving...",
    "projectProps.confirm": "Confirm",
    "projectProps.cancel": "Cancel",
    "projectProps.archiveProject": "Archive project",
    "projectProps.unarchiveProject": "Unarchive project",
    "projectProps.selectCompanyForSecrets": "Select a company to create secrets",
    "projectProps.confirmClearLocalFolder": "Clear local folder from this workspace?",
    "projectProps.confirmDeleteLocalFolder": "Delete this workspace local folder?",
    "projectProps.confirmClearRepo": "Clear repo from this workspace?",
    "projectProps.confirmDeleteRepo": "Delete this workspace repo?",
    "projectProps.name": "Name",
    "projectProps.description": "Description",
    "projectProps.noDescription": "No description",
    "projectProps.lead": "Lead",
    "projectProps.goals": "Goals",
    "projectProps.env": "Env",
    "projectProps.envHelp": "Applied to all runs for issues in this project. Project values override agent env on key conflicts.",
    "projectProps.created": "Created",
    "projectProps.updated": "Updated",
    "projectProps.codebase": "Codebase",
    "projectProps.codebaseHelpLabel": "Codebase help",
    "projectProps.codebaseHelp": "Repo identifies the source of truth. Local folder is the default place agents write code.",
    "projectProps.repo": "Repo",
    "projectProps.changeRepo": "Change repo",
    "projectProps.clearRepo": "Clear repo",
    "projectProps.notSet": "Not set.",
    "projectProps.setRepo": "Set repo",
    "projectProps.localFolder": "Local folder",
    "projectProps.managedFolder": "Paperclip-managed folder.",
    "projectProps.changeLocalFolder": "Change local folder",
    "projectProps.setLocalFolder": "Set local folder",
    "projectProps.clearLocalFolder": "Clear local folder",
    "projectProps.legacyWorkspaces": "Additional legacy workspace records exist on this project. Paperclip is using the primary workspace as the codebase view.",
    "projectProps.noUrl": "No URL",
    "projectProps.save": "Save",
    "projectProps.saveWorkspaceFailed": "Failed to save workspace.",
    "projectProps.deleteWorkspaceFailed": "Failed to delete workspace.",
    "projectProps.updateWorkspaceFailed": "Failed to update workspace.",
    "projectProps.executionWorkspaces": "Execution Workspaces",
    "projectProps.executionWorkspacesHelpLabel": "Execution workspaces help",
    "projectProps.executionWorkspacesHelp": "Project-owned defaults for isolated issue checkouts and execution workspace behavior.",
    "projectProps.enableIsolated": "Enable isolated issue checkouts",
    "projectProps.enableIsolatedHelp": "Let issues choose between the project's primary checkout and an isolated execution workspace.",
    "projectProps.enabled": "Enabled",
    "projectProps.disabled": "Disabled",
    "projectProps.newIssuesIsolated": "New issues default to isolated checkout",
    "projectProps.newIssuesIsolatedHelp": "If disabled, new issues stay on the project's primary checkout unless someone opts in.",
    "projectProps.hideAdvanced": "Hide advanced checkout settings",
    "projectProps.showAdvanced": "Show advanced checkout settings",
    "projectProps.hostManaged": "Host-managed implementation:",
    "projectProps.environment": "Environment",
    "projectProps.noEnvironment": "No environment",
    "projectProps.baseRef": "Base ref",
    "projectProps.branchTemplate": "Branch template",
    "projectProps.worktreeParentDir": "Worktree parent dir",
    "projectProps.provisionCommand": "Provision command",
    "projectProps.teardownCommand": "Teardown command",
    "projectProps.provisionHelp": "Provision runs inside the derived worktree before agent execution. Teardown is stored here for future cleanup flows.",
    "projectProps.dangerZone": "Danger Zone",
    "projectProps.allGoalsLinked": "All goals linked.",
    "projectWorkspaces.empty": "No non-default workspace activity yet.",
    "projectWorkspaces.cleanupAttention": "Cleanup attention needed",
    "projectWorkspace.kind.execution": "Execution workspace",
    "projectWorkspace.kind.project": "Project workspace",
    "projectWorkspace.status.active": "Active",
    "projectWorkspace.status.archived": "Archived",
    "projectWorkspace.status.cleanup_failed": "Cleanup failed",
    "projectWorkspace.status.closing": "Closing",
    "projectWorkspace.updated": "Updated {time}",
    "projectWorkspace.services": "{running}/{total} services",
    "projectWorkspace.stopServices": "Stop services",
    "projectWorkspace.startServices": "Start services",
    "projectWorkspace.retryClose": "Retry close",
    "projectWorkspace.close": "Close workspace",
    "projectWorkspace.branch": "Branch",
    "projectWorkspace.branchCopied": "Branch copied",
    "projectWorkspace.copyBranch": "Copy branch",
    "projectWorkspace.path": "Path",
    "projectWorkspace.pathCopied": "Path copied",
    "projectWorkspace.copyPath": "Copy path",
    "projectWorkspace.service": "Service",
    "projectWorkspace.linkedIssues": "Linked issues",
    "projectWorkspace.moreIssues": "+{count} more",
    "workspaceClose.retryClose": "Retry close",
    "workspaceClose.closeWorkspace": "Close workspace",
    "workspaceClose.retried": "Workspace close retried",
    "workspaceClose.closed": "Workspace closed",
    "workspaceClose.closeFailed": "Failed to close workspace",
    "workspaceClose.unknownError": "Unknown error",
    "workspaceClose.description": "Archive {workspaceName} and clean up the workspace artifacts it owns. Paperclip keeps the workspace record and task history, but removes it from active workspace views.",
    "workspaceClose.checking": "Checking whether this workspace can be closed safely...",
    "workspaceClose.inspectFailed": "Failed to check workspace close readiness.",
    "workspaceClose.blocked": "Close blocked",
    "workspaceClose.readyWithWarnings": "Ready to close, with warnings",
    "workspaceClose.ready": "Ready to close",
    "workspaceClose.sharedSession": "This is a shared workspace session. Archiving removes this session record but keeps the underlying project workspace.",
    "workspaceClose.independentCheckout": "This execution workspace has its own checkout path and can be archived independently.",
    "workspaceClose.primaryPath": "This execution workspace currently points at the project's primary workspace path.",
    "workspaceClose.disposable": "This workspace is disposable and can be archived.",
    "workspaceClose.blockingIssues": "Blocking issues",
    "workspaceClose.blockingReasons": "Blocking reasons",
    "workspaceClose.warnings": "Warnings",
    "workspaceClose.gitStatus": "Git status",
    "workspaceClose.branch": "Branch",
    "workspaceClose.unknown": "Unknown",
    "workspaceClose.baseRef": "Base ref",
    "workspaceClose.notSet": "Not set",
    "workspaceClose.mergedIntoBase": "Merged into base",
    "workspaceClose.yes": "Yes",
    "workspaceClose.no": "No",
    "workspaceClose.aheadBehind": "Ahead / behind",
    "workspaceClose.dirtyTrackedFiles": "Dirty tracked files",
    "workspaceClose.untrackedFiles": "Untracked files",
    "workspaceClose.otherLinkedIssues": "Other linked issues",
    "workspaceClose.runtimeServices": "Additional runtime services",
    "workspaceClose.noDetails": "No more details",
    "workspaceClose.cleanupActions": "Cleanup actions",
    "workspaceClose.cleanupFailedNotice": "This workspace previously failed cleanup. Retrying close reruns cleanup and updates the workspace status after success.",
    "workspaceClose.alreadyArchived": "This workspace is already archived.",
    "workspaceClose.repoRoot": "Repo root:",
    "workspaceClose.workspacePath": "Workspace path:",
    "workspaceClose.lastChecked": "Last checked: {time}",
    "time.justNow": "just now",
    "time.minutesAgo": "{count}m ago",
    "time.hoursAgo": "{count}h ago",
    "time.daysAgo": "{count}d ago",
    "time.weeksAgo": "{count}w ago",
    "time.monthsAgo": "{count}mo ago",
    "common.cancel": "Cancel",
    "common.auto": "Auto",
    "common.choose": "Choose",
    "common.close": "Close",
    "common.changed": "Changed:",
    "common.comingSoon": "Coming soon",
    "common.experimental": "Experimental",
    "common.hint": "Hint",
    "common.ok": "OK",
    "common.copy": "Copy",
    "common.copied": "Copied",
    "common.effort.ask": "Ask",
    "common.effort.auto": "Auto",
    "common.effort.high": "High",
    "common.effort.low": "Low",
    "common.effort.max": "Max",
    "common.effort.medium": "Medium",
    "common.effort.minimal": "Minimal",
    "common.effort.plan": "Plan",
    "common.effort.xhigh": "X-High",
    "common.restore": "Restore",
    "common.status.failed": "Failed",
    "common.status.passed": "Passed",
    "common.status.warnings": "Warnings",
    "common.time.last14Days": "Last 14 days",
    "language.toggle": "中文",
    "company.common.actions": "Actions",
    "company.common.access": "Access",
    "company.common.addCompany": "Add company...",
    "company.common.approve": "Approve",
    "company.common.company": "Company",
    "company.common.companySettings": "Company Settings",
    "company.common.done": "Done",
    "company.common.edit": "Edit",
    "company.common.grants": "Grants",
    "company.common.general": "General",
    "company.common.humanMembers": "Human Members",
    "company.common.environments": "Environments",
    "company.common.invites": "Invites",
    "company.common.inviteMembers": "Invite members",
    "company.common.inviteMembersTo": "Invite members to {name}",
    "company.common.manageCompanies": "Manage companies",
    "company.common.noCompanies": "No companies",
    "company.common.noWorkspaces": "No workspaces",
    "company.common.notSet": "Not set",
    "company.common.remove": "Remove",
    "company.common.reject": "Reject",
    "company.common.role": "Role",
    "company.common.selectCompany": "Select company",
    "company.common.selectWorkspace": "Select workspace",
    "company.common.settings": "Settings",
    "company.common.signOut": "Sign out",
    "company.common.signingOut": "Signing out...",
    "company.common.status": "Status",
    "company.common.switchWorkspace": "Switch workspace",
    "company.common.userAccount": "User account",
    "company.common.workspaceSwitcher": "Open workspace switcher",
    "company.common.workspaceSwitcherFor": "Open {name} workspace switcher",
    "company.role.admin": "Admin",
    "company.role.operator": "Operator",
    "company.role.owner": "Owner",
    "company.role.viewer": "Viewer",
    "company.permission.agentsCreate": "Create agents",
    "company.permission.joinsApprove": "Approve join requests",
    "company.permission.tasksAssign": "Assign tasks",
    "company.permission.tasksAssignScope": "Assign scoped tasks",
    "company.permission.tasksManageActiveCheckouts": "Manage active task checkouts",
    "company.permission.usersInvite": "Invite human members and agents",
    "company.permission.usersManagePermissions": "Manage members and grants",
    "company.permission.environmentsManage": "Manage environments",
    "company.access.actionFailed": "Unknown error",
    "company.access.adminNoMembership": "This account can manage access here via instance admin privileges, but does not currently hold an active company membership.",
    "company.access.companyAccess": "Company Access",
    "company.access.description": "Manage user memberships, member status, and explicit permission grants for {name}.",
    "company.access.emptyMembers": "No user memberships found for this company.",
    "company.access.editMember": "Edit member",
    "company.access.editMemberDescription": "Update company role, member status, and explicit grants for {name}.",
    "company.access.failedApproveJoin": "Failed to approve join request",
    "company.access.failedLoadMembers": "Failed to load company members.",
    "company.access.failedRejectJoin": "Failed to reject join request",
    "company.access.failedRemoveMember": "Failed to remove member",
    "company.access.failedUpdateMember": "Failed to update member",
    "company.access.grantSummaryEmpty": "No explicit grants",
    "company.access.humanMembersDescription": "Manage human member company membership, status, and grants here.",
    "company.access.implicitGrants": "Implicit grants from role",
    "company.access.implicitGrantsDescription": "Roles automatically provide implicit grants. Explicit grants below are only for overrides or extra access that should remain even if the role changes.",
    "company.access.implicitGrantsForRole": "{role} currently includes these permissions automatically.",
    "company.access.implicitGrantsNoRole": "No role is selected, so this member currently has no implicit grants.",
    "company.access.explicitGrantSaved": "Explicitly saved for this member.",
    "company.access.includedByRole": "Already implicitly included by the {role} role. Add an explicit grant only if this should remain after role changes.",
    "company.access.inviteMetadataUnavailable": "Invite metadata unavailable",
    "company.access.joinApproved": "Join request approved",
    "company.access.joinContext": "{types} join invite{role}",
    "company.access.joinDefaultRole": " • default role {role}",
    "company.access.joinRejected": "Join request rejected",
    "company.access.loading": "Loading company access...",
    "company.access.memberRemoved": "Member removed",
    "company.access.memberUpdated": "Member updated",
    "company.access.memberStatus": "Member status",
    "company.access.role": "Company role",
    "company.access.saveAccessSettings": "Save access settings",
    "company.access.saving": "Saving...",
    "company.access.removeMember": "Remove member",
    "company.access.removing": "Removing...",
    "company.access.removeMemberDescription": "Archive {name} and migrate active assignments before hiding this user from assignment fields.",
    "company.access.reassignment": "Issue reassignment",
    "company.access.checkingAssignedIssues": "Checking assigned issues...",
    "company.access.openAssignedIssues": "{count} open assigned issues",
    "company.access.keepUnassigned": "Keep unassigned",
    "company.access.agents": "Agents",
    "company.access.moreIssues": "+{count} more issues",
    "company.access.thisMember": "this member",
    "company.access.cannotRemoveSelf": "You cannot remove yourself.",
    "company.status.active": "Active",
    "company.status.pending": "Pending",
    "company.status.suspended": "Suspended",
    "company.status.archived": "Archived",
    "company.access.noEmail": "No email available",
    "company.access.pendingCount": "{count} pending",
    "company.access.pendingHumanJoins": "Pending Human Member Joins",
    "company.access.pendingHumanJoinsDescription": "Review human member join requests before they become active company members.",
    "company.access.removedAssignments": "Cleared {count} assigned issues.",
    "company.access.selectCompany": "Select a company to manage access.",
    "company.access.submittedAt": "Submitted {time}",
    "company.access.unauthorized": "You do not have permission to manage company members.",
    "company.access.unknownRequester": "Unknown human requester",
    "pathDialog.title": "Specify path manually",
    "pathDialog.description": "Browser security blocks apps from reading full local paths via a file picker. Copy the absolute path and paste it into the input.",
    "pathDialog.mac": "macOS (Finder)",
    "pathDialog.mac.step1": "Find the folder in Finder.",
    "pathDialog.mac.step2": "Hold Option and right-click the folder.",
    "pathDialog.mac.step3": "Click \"Copy <folder name> as Pathname\".",
    "pathDialog.windows": "Windows (File Explorer)",
    "pathDialog.windows.step1": "Find the folder in File Explorer.",
    "pathDialog.windows.step2": "Hold Shift and right-click the folder.",
    "pathDialog.windows.step3": "Click \"Copy as path\".",
    "pathDialog.stepPaste": "Paste the result into the path input.",
    "pathDialog.terminal": "Terminal fallback (macOS/Linux)",
    "pathDialog.terminal.step1": "Run",
    "pathDialog.terminal.step2": "Run",
    "pathDialog.terminal.step3": "Copy the output and paste it into the path input.",
    "pathInstructions.title": "How to get a full path",
    "pathInstructions.description": "Paste the absolute path (e.g. {path}) into the input field.",
    "pathInstructions.mac.step1": "Open Finder and navigate to the folder.",
    "pathInstructions.mac.step2": "Right-click (or Control-click) the folder.",
    "pathInstructions.mac.step3": "Hold the Option key. \"Copy\" changes to \"Copy as Pathname\".",
    "pathInstructions.mac.step4": "Click \"Copy as Pathname\", then paste here.",
    "pathInstructions.mac.tip": "You can also open Terminal, type cd, drag the folder into the terminal window, and press Enter. Then type pwd to see the full path.",
    "pathInstructions.windows.step1": "Open File Explorer and navigate to the folder.",
    "pathInstructions.windows.step2": "Click in the address bar at the top. The full path will appear.",
    "pathInstructions.windows.step3": "Copy the path, then paste here.",
    "pathInstructions.windows.tip": "Alternatively, hold Shift and right-click the folder, then select \"Copy as path\".",
    "pathInstructions.linux.step1": "Open a terminal and navigate to the directory with cd.",
    "pathInstructions.linux.step2": "Run pwd to print the full path.",
    "pathInstructions.linux.step3": "Copy the output and paste here.",
    "pathInstructions.linux.tip": "In most file managers, Ctrl+L reveals the full path in the address bar.",
  },
  zh: {
    "agent.action.approve": "批准代理",
    "agent.action.assignTask": "分配任务",
    "agent.action.copyId": "复制代理 ID",
    "agent.action.create": "创建代理",
    "agent.action.creating": "创建中...",
    "agent.action.new": "新建代理",
    "agent.action.pause": "暂停",
    "agent.action.resetSessions": "重置会话",
    "agent.action.resume": "恢复",
    "agent.action.runHeartbeat": "运行心跳",
    "agent.action.runNow": "立即运行",
    "agent.action.terminate": "终止",
    "agent.action.test": "测试代理",
    "agent.action.testing": "测试中...",
    "agent.breadcrumb.agent": "代理",
    "agent.breadcrumb.agents": "代理",
    "agent.breadcrumb.budget": "预算",
    "agent.breadcrumb.configuration": "配置",
    "agent.breadcrumb.dashboard": "概览",
    "agent.breadcrumb.instructions": "指令",
    "agent.breadcrumb.run": "运行 {id}",
    "agent.breadcrumb.runs": "运行记录",
    "agent.breadcrumb.skills": "技能",
    "agent.config.adapter": "适配器",
    "agent.config.adapterType": "适配器类型",
    "agent.config.advancedRunPolicy": "高级运行策略",
    "agent.config.bootstrapPrompt": "启动提示（旧版）",
    "agent.config.capabilities": "能力说明",
    "agent.config.cheapModel": "低成本模型",
    "agent.config.cheapModelDescription": "当运行请求低成本配置时使用（例如例行摘要）。主模型保持不变。",
    "agent.config.cheapModelNoDefault": "未选择低成本模型，且适配器没有默认值。低成本通道运行会继续使用主模型，并附带兜底说明。",
    "agent.config.cheapModelPlaceholder": "无适配器默认值，请选择低成本模型",
    "agent.config.cheapModelUsesDefault": "未显式选择低成本模型，运行时会回退到 {model}。",
    "agent.config.command": "命令",
    "agent.config.capabilitiesPlaceholder": "描述这个代理能做什么...",
    "agent.config.companyDefaultLocal": "公司默认（本地）",
    "agent.config.continuationAttempts": "续跑次数",
    "agent.config.continuationDelay": "续跑延迟（秒）",
    "agent.config.continueAfterMaxTurn": "达到 turn 上限后继续",
    "agent.config.cooldown": "冷却时间（秒）",
    "agent.config.defaultEnvironment": "默认环境",
    "agent.config.defaultEnvironmentHint": "代理级默认执行目标。项目和任务设置仍可覆盖该值。",
    "agent.config.environmentVariables": "环境变量",
    "agent.config.environmentTestFailed": "环境测试失败",
    "agent.config.execution": "执行",
    "agent.config.extraArgs": "额外参数（逗号分隔）",
    "agent.config.extraArgsPlaceholder": "例如 --verbose, --foo=bar",
    "agent.config.heartbeatInterval": "定时心跳",
    "agent.config.identity": "身份",
    "agent.config.interruptGrace": "中断宽限期（秒）",
    "agent.config.maxConcurrentRuns": "最大并发运行数",
    "agent.config.name": "名称",
    "agent.config.permissions": "权限",
    "agent.config.permissionsAndConfiguration": "权限和配置",
    "agent.config.primaryModel": "主模型",
    "agent.config.promptTemplate": "提示模板",
    "agent.config.promptTemplatePlaceholder": "你是代理 {{ agent.name }}。你的角色是 {{ agent.role }}...",
    "agent.config.promptTemplateWarning": "提示模板会在每次心跳重复发送。请保持简短动态，避免持续产生 token 成本和缓存抖动。",
    "agent.config.runEveryPrefix": "每",
    "agent.config.runEverySuffix": "秒运行一次心跳",
    "agent.config.runPolicy": "运行策略",
    "agent.config.save": "保存",
    "agent.config.saving": "保存中...",
    "agent.config.bootstrapPromptPlaceholder": "首次运行使用的可选初始设置提示",
    "agent.config.bootstrapPromptWarning": "启动提示属于旧版配置，将在未来版本移除。建议把这段内容迁移到代理提示模板或指令文件。",
    "agent.config.cheapModelUsesDefaultPrefix": "未显式选择低成本模型，运行时会回退到",
    "agent.config.test": "测试",
    "agent.config.thinkingEffort": "推理强度",
    "agent.config.timeout": "超时（秒）",
    "agent.config.title": "职称",
    "agent.config.titlePlaceholder": "例如工程副总裁",
    "agent.config.model": "模型",
    "agent.config.unsavedChanges": "有未保存的更改",
    "agent.config.wakeOnDemand": "按需唤醒",
    "agent.config.workingDirectoryDeprecated": "工作目录（已弃用）",
    "agent.detail.apiKeys": "API 密钥",
    "agent.detail.approvalPending": "此代理正在等待董事会审批，暂时无法调用。",
    "agent.detail.cachedTokens": "缓存 tokens",
    "agent.detail.canAssignTasks": "可以分配任务",
    "agent.detail.canCreateAgents": "可以创建新代理",
    "agent.detail.configRevisions": "配置修订",
    "agent.detail.cost": "成本",
    "agent.detail.costs": "成本",
    "agent.detail.date": "日期",
    "agent.detail.input": "输入",
    "agent.detail.inputTokens": "输入 tokens",
    "agent.detail.moreIssues": "还有 {count} 个任务",
    "agent.detail.noConfigRevisions": "暂无配置修订。",
    "agent.detail.noTrackedChanges": "没有跟踪到变更",
    "agent.detail.noRecentIssues": "暂无最近任务。",
    "agent.detail.output": "输出",
    "agent.detail.outputTokens": "输出 tokens",
    "agent.detail.permissionsDescription": "允许此代理创建或雇佣代理，并隐式具备任务分配能力。",
    "agent.detail.recentIssues": "最近任务",
    "agent.detail.run": "运行",
    "agent.detail.runActivity": "运行活动",
    "agent.detail.seeAll": "查看全部 →",
    "agent.detail.successRate": "成功率",
    "agent.detail.taskAssign.ceoRole": "CEO 代理会自动启用。",
    "agent.detail.taskAssign.creator": "当此代理可以创建新代理时会自动启用。",
    "agent.detail.taskAssign.disabled": "默认禁用，除非显式授权。",
    "agent.detail.taskAssign.explicit": "已通过公司权限显式授权。",
    "agent.detail.totalCost": "总成本",
    "agent.detail.byPriority": "按优先级统计任务",
    "agent.detail.byStatus": "按状态统计任务",
    "agent.instructions.advanced": "高级",
    "agent.instructions.availableLocalOnly": "指令包仅适用于本地适配器。",
    "agent.instructions.copyMarkdown": "复制为 Markdown",
    "agent.instructions.create": "创建",
    "agent.instructions.delete": "删除",
    "agent.instructions.deleteConfirm": "删除 {file}？",
    "agent.instructions.deprecatedVirtualFile": "已弃用的虚拟文件",
    "agent.instructions.entryFile": "入口文件",
    "agent.instructions.entryFileHint": "代理加载指令时首先读取的主文件。默认是 AGENTS.md。",
    "agent.instructions.external": "外部",
    "agent.instructions.fileContents": "文件内容",
    "agent.instructions.files": "文件",
    "agent.instructions.fileType": "{language} 文件",
    "agent.instructions.managed": "托管",
    "agent.instructions.managedPath": "（托管）",
    "agent.instructions.mode": "模式",
    "agent.instructions.modeHint": "托管：Paperclip 存储并提供指令包。外部：你提供指令所在的磁盘路径。",
    "agent.instructions.newFileInBundle": "此指令包中的新文件",
    "agent.instructions.placeholder": "# 代理指令",
    "agent.instructions.rootPath": "根路径",
    "agent.instructions.rootPathHint": "指令包在磁盘上的绝对目录。托管模式下由 Paperclip 自动设置。",
    "agent.instructions.virtualFile": "虚拟文件",
    "agent.instructions.virtualFileHint": "旧版内联提示，此已弃用的虚拟文件用于保留旧 promptTemplate 内容",
    "agent.error.couldNotSave": "无法保存代理",
    "agent.error.openCodeExplicitModel": "OpenCode 需要使用 provider/model 格式显式指定模型。",
    "agent.error.noAgentReference": "没有代理引用",
    "agent.error.resetSessionFailed": "重置会话失败",
    "agent.error.saveFailed": "保存失败",
    "agent.error.actionFailed": "操作失败",
    "agent.error.selectCompanyCreateSecrets": "请选择公司以创建密钥",
    "agent.error.selectCompanyDetectModel": "请选择公司以检测模型",
    "agent.error.selectCompanyTestEnvironment": "请选择公司以测试适配器环境",
    "agent.error.selectCompanyUploadImages": "请选择公司以上传图片",
    "agent.error.updatePermissionsFailed": "更新权限失败",
    "agent.keys.active": "有效密钥",
    "agent.keys.banner": "API 密钥已创建。请立即复制，之后不会再次显示。",
    "agent.keys.create": "创建 API 密钥",
    "agent.keys.defaultName": "默认",
    "agent.keys.description": "API 密钥允许此代理向 Paperclip 服务器发起认证调用。",
    "agent.keys.dismiss": "关闭",
    "agent.keys.hide": "隐藏",
    "agent.keys.copied": "已复制！",
    "agent.keys.created": "创建于",
    "agent.keys.loading": "正在加载密钥...",
    "agent.keys.namePlaceholder": "密钥名称（例如 production）",
    "agent.keys.noActive": "没有有效 API 密钥。",
    "agent.keys.revoked": "已撤销密钥",
    "agent.keys.revokedAt": "撤销于",
    "agent.keys.revoke": "撤销",
    "agent.keys.show": "显示",
    "agent.run.adapter": "适配器：",
    "agent.run.after": "之后",
    "agent.run.assignment": "任务分配",
    "agent.run.automation": "自动化",
    "agent.run.backToRuns": "返回运行记录",
    "agent.run.baseRef": "基准引用：",
    "agent.run.before": "之前",
    "agent.run.branch": "分支：",
    "agent.run.cached": "缓存",
    "agent.run.cancel": "取消",
    "agent.run.cancelling": "正在取消...",
    "agent.run.clearSession": "清除此类任务的会话",
    "agent.run.clearSessionConfirm": "清除此运行触达的 {count} 个任务会话吗？",
    "agent.run.clearingSession": "正在清除会话...",
    "agent.run.cleanup": "清理：",
    "agent.run.command": "命令：",
    "agent.run.commandNotes": "命令说明",
    "agent.run.context": "上下文",
    "agent.run.cost": "成本",
    "agent.run.createdByRun": "由本次运行创建",
    "agent.run.details": "详情",
    "agent.run.duration": "耗时：",
    "agent.run.environment": "环境",
    "agent.run.error": "错误：",
    "agent.run.events": "事件（{count}）",
    "agent.run.exitCode": "退出码 {code}",
    "agent.run.failureDetails": "失败详情",
    "agent.run.failedClearSessions": "清除会话失败",
    "agent.run.failedLoadLog": "加载运行日志失败",
    "agent.run.failedLoadMoreLog": "加载更多运行日志失败",
    "agent.run.failedLoadWorkspaceLog": "加载工作区操作日志失败",
    "agent.run.failedResume": "恢复运行失败",
    "agent.run.failedRetry": "重试运行失败",
    "agent.run.failedClaudeLogin": "运行 Claude 登录失败",
    "agent.run.hideFullLog": "隐藏完整日志",
    "agent.run.input": "输入",
    "agent.run.invocation": "调用",
    "agent.run.issuesTouched": "触达任务（{count}）",
    "agent.run.jumpToLive": "跳到实时位置",
    "agent.run.latestRun": "最近运行",
    "agent.run.live": "实时",
    "agent.run.liveRun": "实时运行",
    "agent.run.loadMoreLog": "加载更多日志",
    "agent.run.loading": "加载中...",
    "agent.run.loadingLog": "正在加载日志...",
    "agent.run.loadingRunLogs": "正在加载运行日志...",
    "agent.run.loginToClaude": "登录 Claude Code",
    "agent.run.loginUrl": "登录 URL：",
    "agent.run.noLogEvents": "没有日志事件。",
    "agent.run.noPersistedLogLines": "没有持久化日志行。",
    "agent.run.noPersistedTranscript": "此运行没有持久化转录。",
    "agent.run.noRuns": "暂无运行记录。",
    "agent.run.onDemand": "按需",
    "agent.run.output": "输出",
    "agent.run.prompt": "提示",
    "agent.run.repoRoot": "仓库根目录：",
    "agent.run.resume": "恢复",
    "agent.run.resumeSkipped": "恢复请求已跳过。",
    "agent.run.resuming": "恢复中...",
    "agent.run.retry": "重试",
    "agent.run.retrySkipped": "重试已跳过。",
    "agent.run.retrying": "重试中...",
    "agent.run.reusedWorkspace": "复用已有工作区",
    "agent.run.session": "会话",
    "agent.run.sessionChanged": "（已变化）",
    "agent.run.showFullLog": "显示完整日志",
    "agent.run.signal": "（信号：{signal}）",
    "agent.run.showingLogBytes": "正在显示前 {shown} KB",
    "agent.run.showingLogBytesOf": "正在显示前 {shown} KB，共 {total} KB",
    "agent.run.stderrExcerpt": "stderr 摘录",
    "agent.run.stdoutExcerpt": "stdout 摘录",
    "agent.run.timer": "定时器",
    "agent.run.transcript": "转录（{count}）",
    "agent.run.waitingTranscript": "正在等待转录...",
    "agent.run.workingDir": "工作目录：",
    "agent.run.workspace": "工作区（{count}）",
    "agent.run.worktree": "工作树：",
    "agent.run.phase.worktree_prepare": "工作树设置",
    "agent.run.phase.workspace_provision": "工作区准备",
    "agent.run.phase.workspace_teardown": "工作区销毁",
    "agent.run.phase.worktree_cleanup": "工作树清理",
    "agent.skills.adapter": "适配器",
    "agent.skills.applied": "已应用技能",
    "agent.skills.appliedEphemeral": "在代理运行时应用",
    "agent.skills.appliedPersistent": "保留在工作区中",
    "agent.skills.appliedTrackedOnly": "仅跟踪",
    "agent.skills.appliedUnknown": "未知",
    "agent.skills.companyLibrary": "查看公司技能库",
    "agent.skills.importFirst": "请先把技能导入公司技能库，然后在这里附加。",
    "agent.skills.location": "位置：",
    "agent.skills.manageInAdapter": "请直接在适配器中管理技能。",
    "agent.skills.missing": "请求的技能不在公司技能库中",
    "agent.skills.required": "Paperclip 必需",
    "agent.skills.savingChanges": "正在保存更改...",
    "agent.skills.savingSoon": "即将保存...",
    "agent.skills.selected": "已选技能",
    "agent.skills.unsupportedAcp": "Paperclip 暂不支持管理自定义 ACP 命令的技能。",
    "agent.skills.unsupportedAdapter": "Paperclip 暂不支持管理此适配器的技能。请直接在适配器中管理。",
    "agent.skills.unsupportedOpenClaw": "这里无法管理 OpenClaw 技能。请前往你的 OpenClaw 实例管理此代理的技能。",
    "agent.skills.updateFailed": "更新技能失败",
    "agent.skills.unmanaged": "（{count}）用户安装的技能，不由 Paperclip 管理",
    "agent.skills.view": "查看",
    "agent.form.companySkills": "公司技能",
    "agent.form.companySkillsDescription": "可从公司技能库中选择附加技能。Paperclip 内置运行时技能会自动添加。",
    "agent.form.createFailed": "创建代理失败",
    "agent.form.firstAgentCeo": "这将作为 CEO 代理创建",
    "agent.form.noOptionalSkills": "还没有安装可选公司技能。",
    "agent.form.subtitle": "配置代理身份、汇报关系和执行方式",
    "agent.form.titlePlaceholder": "职称（例如工程副总裁）",
    "agent.help.adapterType": "该代理的运行方式：本地 CLI（Claude/Codex/OpenCode）、OpenClaw Gateway、派生进程或通用 HTTP webhook。",
    "agent.help.bootstrapPrompt": "仅在 Paperclip 启动新会话时发送。用于稳定的初始设置指引，不应在每次心跳重复发送。",
    "agent.help.capabilities": "描述该代理能做什么，会显示在组织图中并用于任务路由。",
    "agent.help.cooldownSec": "该代理连续两次心跳运行之间的最小间隔秒数。",
    "agent.help.cwd": "已弃用的本地适配器工作目录兜底配置。旧代理可能仍有该值，新配置应改用项目工作区。",
    "agent.help.envVars": "注入适配器进程的环境变量。可使用明文值或 secret 引用。",
    "agent.help.extraArgs": "本地适配器的额外 CLI 参数，使用逗号分隔。",
    "agent.help.graceSec": "发送中断后等待多少秒再强制终止进程。",
    "agent.help.heartbeatInterval": "按定时器自动运行该代理。适合周期性检查新工作等任务。",
    "agent.help.intervalSec": "两次自动心跳调用之间的秒数。",
    "agent.help.localCommand": "覆盖适配器要调用的 CLI 命令路径（例如 /usr/local/bin/claude、codex、opencode）。",
    "agent.help.maxConcurrentRuns": "该代理可同时执行的心跳运行数量上限。",
    "agent.help.maxTurnContinuationDelaySec": "每次 max-turn 续跑前等待的秒数。",
    "agent.help.maxTurnContinuationEnabled": "当适配器因单次运行 turn 上限耗尽而停止时，自动排队有限的续跑。",
    "agent.help.maxTurnContinuationMaxAttempts": "一次 max-turn 停止后的最大自动续跑次数。它独立于单次运行 turn 上限。",
    "agent.help.model": "覆盖适配器默认使用的模型。",
    "agent.help.name": "此代理的显示名称。",
    "agent.help.promptTemplate": "每次心跳都会发送。保持简短动态，用于当前任务上下文，不要放大量静态指令。支持 {{ agent.id }}、{{ agent.name }}、{{ agent.role }} 等模板变量。",
    "agent.help.reportsTo": "该代理在组织层级中汇报给谁。",
    "agent.help.thinkingEffort": "控制模型推理深度。支持值会随适配器和模型变化。",
    "agent.help.timeoutSec": "单次运行最多可持续的秒数，0 表示不限制。",
    "agent.help.title": "显示在组织图中的职称。",
    "agent.help.wakeOnDemand": "允许通过任务分配、API 调用、UI 操作或自动化系统唤醒该代理。",
    "agent.list.count": "{count} 个代理",
    "agent.list.empty": "创建第一个代理后即可开始。",
    "agent.list.filter.active": "活跃",
    "agent.list.filter.all": "全部",
    "agent.list.filter.error": "异常",
    "agent.list.filter.paused": "已暂停",
    "agent.list.filters": "筛选",
    "agent.list.live": "运行中{count}",
    "agent.list.noFilterMatch": "没有代理符合当前筛选条件。",
    "agent.list.noOrg": "尚未定义组织层级。",
    "agent.list.selectCompany": "请选择公司以查看代理。",
    "agent.list.showTerminated": "显示已终止",
    "agent.model.default": "默认",
    "agent.model.detect": "检测模型",
    "agent.model.detectFromConfig": "从配置检测",
    "agent.model.detected": "已检测",
    "agent.model.detecting": "检测中...",
    "agent.model.empty": "未找到模型。",
    "agent.model.emptyDetect": "未检测到模型。请选择一个模型，或手动输入。",
    "agent.model.emptyDetectManual": "尚未检测到模型。请手动输入 provider/model。",
    "agent.model.current": "当前",
    "agent.model.loadFailed": "加载适配器模型失败。",
    "agent.model.manual": "使用手动模型",
    "agent.model.openCodeLocalOnly": "OpenCode 实时模型发现仅支持本地环境。当前将为 {environment} 使用内置列表和手动输入。",
    "agent.model.redetect": "重新检测配置",
    "agent.model.refresh": "刷新模型",
    "agent.model.refreshFailed": "刷新适配器模型失败。",
    "agent.model.refreshing": "刷新中...",
    "agent.model.search": "搜索模型...",
    "agent.model.searchCreate": "搜索模型...（输入以创建）",
    "agent.model.select": "选择模型",
    "agent.model.selectRequired": "选择模型（必填）",
    "agent.properties.adapter": "适配器",
    "agent.properties.created": "创建时间",
    "agent.properties.lastError": "最近错误",
    "agent.properties.lastHeartbeat": "最近心跳",
    "agent.properties.reportsTo": "汇报给",
    "agent.properties.role": "角色",
    "agent.properties.session": "会话",
    "agent.properties.status": "状态",
    "agent.properties.title": "职称",
    "agent.reports.choose": "选择汇报对象...",
    "agent.reports.chooseManager": "选择主管...",
    "agent.reports.currentTerminated": "当前：{name}（已终止）",
    "agent.reports.disabledCeo": "汇报给：无（CEO）",
    "agent.reports.manager": "汇报给 {name}{suffix}",
    "agent.reports.missing": "已保存的主管不在当前公司中。请选择新的主管或清空该字段。",
    "agent.reports.noManager": "无主管",
    "agent.reports.terminatedSuffix": "（已终止）",
    "agent.reports.unknown": "未知主管（旧 ID）",
    "agent.role.designer": "设计师",
    "agent.role.devops": "运维",
    "agent.role.engineer": "工程师",
    "agent.role.general": "通用",
    "agent.role.pm": "产品经理",
    "agent.role.qa": "测试",
    "agent.role.researcher": "研究员",
    "agent.role.security": "安全",
    "account.board": "董事会",
    "account.signedIn": "已登录",
    "account.localBoard": "本地工作区董事会",
    "account.badge.authenticated": "账号",
    "account.badge.local": "本地",
    "account.openMenu": "打开账号菜单",
    "account.viewProfile": "查看个人资料",
    "account.viewProfileDescription": "查看你的动态、任务和使用记录。",
    "account.editProfile": "编辑个人资料",
    "account.editProfileDescription": "更新显示名称和头像。",
    "account.instanceSettings": "实例设置",
    "account.instanceSettingsDescription": "返回上次打开的设置页。",
    "account.docs": "文档",
    "account.docsDescription": "在新标签页打开 Paperclip 文档。",
    "account.language": "语言",
    "account.languageDescription": "在中文和英文之间切换。",
    "account.themeLight": "切换到浅色模式",
    "account.themeDark": "切换到深色模式",
    "account.themeDescription": "切换应用外观。",
    "account.signingOut": "正在退出...",
    "account.signOut": "退出登录",
    "account.signOutDescription": "结束当前浏览器会话。",
    "project.status.backlog": "待整理",
    "project.status.planned": "已计划",
    "project.status.in_progress": "进行中",
    "project.status.completed": "已完成",
    "project.status.cancelled": "已取消",
    "project.fallback": "项目",
    "project.breadcrumb": "项目",
    "project.description.placeholder": "添加描述...",
    "project.field.status": "状态",
    "project.field.targetDate": "目标日期",
    "project.color.change": "更改项目颜色",
    "project.color.select": "选择颜色 {color}",
    "project.toast.archived": "\"{name}\" 已归档",
    "project.toast.unarchived": "\"{name}\" 已取消归档",
    "project.toast.archiveFailed": "项目归档失败",
    "project.toast.unarchiveFailed": "取消项目归档失败",
    "project.error.noCompany": "未选择公司",
    "project.pausedByBudget": "已因预算硬停暂停",
    "project.managedBy": "由 {name} 管理",
    "project.tab.issues": "任务",
    "project.tab.overview": "概览",
    "project.tab.pluginOperations": "插件操作",
    "project.tab.workspaces": "工作区",
    "project.tab.configuration": "配置",
    "project.tab.budget": "预算",
    "project.loadingWorkspaces": "正在加载工作区...",
    "projectDialog.localFolderName": "本地文件夹",
    "projectDialog.githubRepoName": "GitHub 仓库",
    "projectDialog.error.localFolderAbsolute": "本地文件夹必须是完整的绝对路径。",
    "projectDialog.error.repoUrl": "仓库必须使用有效的 GitHub 或 GitHub Enterprise 仓库 URL。",
    "projectDialog.title": "新建项目",
    "projectDialog.namePlaceholder": "项目名称",
    "projectDialog.descriptionPlaceholder": "添加描述...",
    "projectDialog.repoUrl": "仓库 URL",
    "projectDialog.optional": "可选",
    "projectDialog.repoHelp": "关联 GitHub 仓库后，代理可以为此项目克隆、读取并推送代码。",
    "projectDialog.localFolder": "本地文件夹",
    "projectDialog.localFolderHelp": "设置此机器上的绝对路径，本地代理会在这里读写项目文件。",
    "projectDialog.removeGoal": "移除目标 {title}",
    "projectDialog.addGoal": "+ 目标",
    "projectDialog.goal": "目标",
    "projectDialog.noGoal": "不关联目标",
    "projectDialog.allGoalsSelected": "已选择所有目标。",
    "projectDialog.targetDate": "目标日期",
    "projectDialog.createFailed": "创建项目失败。",
    "projectDialog.creating": "正在创建...",
    "projectDialog.create": "创建项目",
    "projectProps.saving": "保存中",
    "projectProps.saved": "已保存",
    "projectProps.failed": "失败",
    "projectProps.archive": "归档",
    "projectProps.unarchive": "取消归档",
    "projectProps.archiveDescription": "归档此项目后，它会从侧边栏和项目选择器中隐藏。",
    "projectProps.unarchiveDescription": "取消归档此项目后，它会恢复到侧边栏和项目选择器中。",
    "projectProps.archiving": "正在归档...",
    "projectProps.unarchiving": "正在取消归档...",
    "projectProps.confirm": "确认",
    "projectProps.cancel": "取消",
    "projectProps.archiveProject": "归档项目",
    "projectProps.unarchiveProject": "取消归档项目",
    "projectProps.selectCompanyForSecrets": "请选择公司后再创建密钥",
    "projectProps.confirmClearLocalFolder": "要从此工作区清除本地文件夹吗？",
    "projectProps.confirmDeleteLocalFolder": "要删除此工作区的本地文件夹吗？",
    "projectProps.confirmClearRepo": "要从此工作区清除仓库吗？",
    "projectProps.confirmDeleteRepo": "要删除此工作区的仓库吗？",
    "projectProps.name": "名称",
    "projectProps.description": "描述",
    "projectProps.noDescription": "暂无描述",
    "projectProps.lead": "负责人",
    "projectProps.goals": "目标",
    "projectProps.env": "环境变量",
    "projectProps.envHelp": "应用于此项目中所有任务的运行。键名冲突时，项目值会覆盖代理环境变量。",
    "projectProps.created": "创建时间",
    "projectProps.updated": "更新时间",
    "projectProps.codebase": "代码库",
    "projectProps.codebaseHelpLabel": "代码库说明",
    "projectProps.codebaseHelp": "仓库用于标识代码来源。本地文件夹是代理默认写入代码的位置。",
    "projectProps.repo": "仓库",
    "projectProps.changeRepo": "更改仓库",
    "projectProps.clearRepo": "清除仓库",
    "projectProps.notSet": "未设置。",
    "projectProps.setRepo": "设置仓库",
    "projectProps.localFolder": "本地文件夹",
    "projectProps.managedFolder": "Paperclip 管理的文件夹。",
    "projectProps.changeLocalFolder": "更改本地文件夹",
    "projectProps.setLocalFolder": "设置本地文件夹",
    "projectProps.clearLocalFolder": "清除本地文件夹",
    "projectProps.legacyWorkspaces": "此项目还有额外的旧版工作区记录。Paperclip 正在使用主工作区作为代码库视图。",
    "projectProps.noUrl": "无 URL",
    "projectProps.save": "保存",
    "projectProps.saveWorkspaceFailed": "保存工作区失败。",
    "projectProps.deleteWorkspaceFailed": "删除工作区失败。",
    "projectProps.updateWorkspaceFailed": "更新工作区失败。",
    "projectProps.executionWorkspaces": "执行工作区",
    "projectProps.executionWorkspacesHelpLabel": "执行工作区说明",
    "projectProps.executionWorkspacesHelp": "项目级默认设置，用于隔离任务检出和执行工作区行为。",
    "projectProps.enableIsolated": "启用隔离任务检出",
    "projectProps.enableIsolatedHelp": "允许任务在项目主检出和隔离执行工作区之间选择。",
    "projectProps.enabled": "已启用",
    "projectProps.disabled": "已禁用",
    "projectProps.newIssuesIsolated": "新任务默认使用隔离检出",
    "projectProps.newIssuesIsolatedHelp": "如果关闭，新任务会留在项目主检出中，除非手动选择隔离。",
    "projectProps.hideAdvanced": "隐藏高级检出设置",
    "projectProps.showAdvanced": "显示高级检出设置",
    "projectProps.hostManaged": "主机管理实现：",
    "projectProps.environment": "环境",
    "projectProps.noEnvironment": "无环境",
    "projectProps.baseRef": "基准引用",
    "projectProps.branchTemplate": "分支模板",
    "projectProps.worktreeParentDir": "Worktree 父目录",
    "projectProps.provisionCommand": "预置命令",
    "projectProps.teardownCommand": "清理命令",
    "projectProps.provisionHelp": "预置命令会在代理执行前于派生 worktree 中运行。清理命令会保存在这里，供后续清理流程使用。",
    "projectProps.dangerZone": "危险区域",
    "projectProps.allGoalsLinked": "已关联所有目标。",
    "projectWorkspaces.empty": "暂无非默认工作区活动。",
    "projectWorkspaces.cleanupAttention": "需要处理清理问题",
    "projectWorkspace.kind.execution": "执行工作区",
    "projectWorkspace.kind.project": "项目工作区",
    "projectWorkspace.status.active": "活跃",
    "projectWorkspace.status.archived": "已归档",
    "projectWorkspace.status.cleanup_failed": "清理失败",
    "projectWorkspace.status.closing": "正在关闭",
    "projectWorkspace.updated": "更新于 {time}",
    "projectWorkspace.services": "{running}/{total} 个服务",
    "projectWorkspace.stopServices": "停止服务",
    "projectWorkspace.startServices": "启动服务",
    "projectWorkspace.retryClose": "重试关闭",
    "projectWorkspace.close": "关闭工作区",
    "projectWorkspace.branch": "分支",
    "projectWorkspace.branchCopied": "分支已复制",
    "projectWorkspace.copyBranch": "复制分支",
    "projectWorkspace.path": "路径",
    "projectWorkspace.pathCopied": "路径已复制",
    "projectWorkspace.copyPath": "复制路径",
    "projectWorkspace.service": "服务",
    "projectWorkspace.linkedIssues": "关联任务",
    "projectWorkspace.moreIssues": "另有 {count} 个",
    "workspaceClose.retryClose": "重试关闭",
    "workspaceClose.closeWorkspace": "关闭工作区",
    "workspaceClose.retried": "已重试关闭工作区",
    "workspaceClose.closed": "工作区已关闭",
    "workspaceClose.closeFailed": "关闭工作区失败",
    "workspaceClose.unknownError": "未知错误",
    "workspaceClose.description": "归档 {workspaceName} 并清理它拥有的工作区产物。Paperclip 会保留工作区记录和任务历史，但会将它从活跃工作区视图中移除。",
    "workspaceClose.checking": "正在检查此工作区是否可以安全关闭...",
    "workspaceClose.inspectFailed": "检查工作区关闭条件失败。",
    "workspaceClose.blocked": "关闭受阻",
    "workspaceClose.readyWithWarnings": "可关闭，但有警告",
    "workspaceClose.ready": "可关闭",
    "workspaceClose.sharedSession": "这是共享工作区会话。归档会移除此会话记录，但保留底层项目工作区。",
    "workspaceClose.independentCheckout": "此执行工作区有自己的检出路径，可以独立归档。",
    "workspaceClose.primaryPath": "此执行工作区当前指向项目的主工作区路径。",
    "workspaceClose.disposable": "此工作区是可丢弃的，可以归档。",
    "workspaceClose.blockingIssues": "阻塞任务",
    "workspaceClose.blockingReasons": "阻塞原因",
    "workspaceClose.warnings": "警告",
    "workspaceClose.gitStatus": "Git 状态",
    "workspaceClose.branch": "分支",
    "workspaceClose.unknown": "未知",
    "workspaceClose.baseRef": "基准引用",
    "workspaceClose.notSet": "未设置",
    "workspaceClose.mergedIntoBase": "已合并到基准",
    "workspaceClose.yes": "是",
    "workspaceClose.no": "否",
    "workspaceClose.aheadBehind": "领先 / 落后",
    "workspaceClose.dirtyTrackedFiles": "已跟踪改动文件",
    "workspaceClose.untrackedFiles": "未跟踪文件",
    "workspaceClose.otherLinkedIssues": "其他关联任务",
    "workspaceClose.runtimeServices": "附加运行时服务",
    "workspaceClose.noDetails": "无更多详情",
    "workspaceClose.cleanupActions": "清理动作",
    "workspaceClose.cleanupFailedNotice": "此工作区之前清理失败。重试关闭会重新运行清理流程，并在成功后更新工作区状态。",
    "workspaceClose.alreadyArchived": "此工作区已归档。",
    "workspaceClose.repoRoot": "仓库根目录：",
    "workspaceClose.workspacePath": "工作区路径：",
    "workspaceClose.lastChecked": "最近检查：{time}",
    "time.justNow": "刚刚",
    "time.minutesAgo": "{count} 分钟前",
    "time.hoursAgo": "{count} 小时前",
    "time.daysAgo": "{count} 天前",
    "time.weeksAgo": "{count} 周前",
    "time.monthsAgo": "{count} 个月前",
    "common.cancel": "取消",
    "common.auto": "自动",
    "common.choose": "选择",
    "common.close": "关闭",
    "common.changed": "已变更：",
    "common.comingSoon": "即将支持",
    "common.experimental": "实验性",
    "common.hint": "提示",
    "common.ok": "确定",
    "common.copy": "复制",
    "common.copied": "已复制",
    "common.effort.ask": "询问",
    "common.effort.auto": "自动",
    "common.effort.high": "高",
    "common.effort.low": "低",
    "common.effort.max": "最大",
    "common.effort.medium": "中",
    "common.effort.minimal": "最小",
    "common.effort.plan": "规划",
    "common.effort.xhigh": "极高",
    "common.restore": "恢复",
    "common.status.failed": "失败",
    "common.status.passed": "通过",
    "common.status.warnings": "警告",
    "common.time.last14Days": "最近 14 天",
    "language.toggle": "EN",
    "company.common.actions": "操作",
    "company.common.access": "访问",
    "company.common.addCompany": "添加公司...",
    "company.common.approve": "批准",
    "company.common.company": "公司",
    "company.common.companySettings": "公司设置",
    "company.common.done": "完成",
    "company.common.edit": "编辑",
    "company.common.grants": "授权",
    "company.common.general": "常规",
    "company.common.humanMembers": "人类成员",
    "company.common.environments": "环境",
    "company.common.invites": "邀请",
    "company.common.inviteMembers": "邀请成员",
    "company.common.inviteMembersTo": "邀请成员加入 {name}",
    "company.common.manageCompanies": "管理公司",
    "company.common.noCompanies": "没有公司",
    "company.common.noWorkspaces": "没有工作区",
    "company.common.notSet": "未设置",
    "company.common.remove": "移除",
    "company.common.reject": "拒绝",
    "company.common.role": "角色",
    "company.common.selectCompany": "选择公司",
    "company.common.selectWorkspace": "选择工作区",
    "company.common.settings": "设置",
    "company.common.signOut": "退出登录",
    "company.common.signingOut": "正在退出...",
    "company.common.status": "状态",
    "company.common.switchWorkspace": "切换工作区",
    "company.common.userAccount": "用户账号",
    "company.common.workspaceSwitcher": "打开工作区切换器",
    "company.common.workspaceSwitcherFor": "打开 {name} 工作区切换器",
    "company.role.admin": "管理员",
    "company.role.operator": "操作员",
    "company.role.owner": "所有者",
    "company.role.viewer": "查看者",
    "company.permission.agentsCreate": "创建代理",
    "company.permission.joinsApprove": "审批加入请求",
    "company.permission.tasksAssign": "分配任务",
    "company.permission.tasksAssignScope": "分配限定范围任务",
    "company.permission.tasksManageActiveCheckouts": "管理活跃任务签出",
    "company.permission.usersInvite": "邀请人类成员和代理",
    "company.permission.usersManagePermissions": "管理成员和授权",
    "company.permission.environmentsManage": "管理环境",
    "company.access.actionFailed": "未知错误",
    "company.access.adminNoMembership": "此账号可通过实例管理员权限在此管理访问，但当前并未持有活跃的公司成员资格。",
    "company.access.companyAccess": "公司访问",
    "company.access.description": "管理 {name} 的用户成员资格、成员状态和显式权限授权。",
    "company.access.emptyMembers": "此公司尚未找到用户成员资格。",
    "company.access.editMember": "编辑成员",
    "company.access.editMemberDescription": "更新 {name} 的公司角色、成员状态和显式授权。",
    "company.access.failedApproveJoin": "批准加入请求失败",
    "company.access.failedLoadMembers": "加载公司成员失败。",
    "company.access.failedRejectJoin": "拒绝加入请求失败",
    "company.access.failedRemoveMember": "移除成员失败",
    "company.access.failedUpdateMember": "更新成员失败",
    "company.access.grantSummaryEmpty": "无显式授权",
    "company.access.humanMembersDescription": "在这里管理人类成员的公司成员资格、状态和授权。",
    "company.access.implicitGrants": "来自角色的隐式授权",
    "company.access.implicitGrantsDescription": "角色会自动提供隐式授权。下方显式授权仅用于覆盖或添加即使角色变化也应保留的额外访问权限。",
    "company.access.implicitGrantsForRole": "{role} 当前会自动包含这些权限。",
    "company.access.implicitGrantsNoRole": "未选择角色，因此此成员当前没有隐式授权。",
    "company.access.explicitGrantSaved": "已为此成员显式保存。",
    "company.access.includedByRole": "已由{role}角色隐式包含。只有需要在角色变化后保留时才添加显式授权。",
    "company.access.inviteMetadataUnavailable": "邀请元数据不可用",
    "company.access.joinApproved": "加入请求已批准",
    "company.access.joinContext": "{types} 加入邀请{role}",
    "company.access.joinDefaultRole": " • 默认角色 {role}",
    "company.access.joinRejected": "加入请求已拒绝",
    "company.access.loading": "正在加载公司访问...",
    "company.access.memberRemoved": "成员已移除",
    "company.access.memberUpdated": "成员已更新",
    "company.access.memberStatus": "成员状态",
    "company.access.role": "公司角色",
    "company.access.saveAccessSettings": "保存访问设置",
    "company.access.saving": "正在保存...",
    "company.access.removeMember": "移除成员",
    "company.access.removing": "正在移除...",
    "company.access.removeMemberDescription": "归档 {name}，并在从分配字段隐藏该用户前迁移活跃分配。",
    "company.access.reassignment": "问题重新分配",
    "company.access.checkingAssignedIssues": "正在检查已分配问题...",
    "company.access.openAssignedIssues": "{count} 个打开的已分配问题",
    "company.access.keepUnassigned": "保持未分配",
    "company.access.agents": "代理",
    "company.access.moreIssues": "还有 {count} 个问题",
    "company.access.thisMember": "此成员",
    "company.access.cannotRemoveSelf": "不能移除你自己。",
    "company.status.active": "活跃",
    "company.status.pending": "待处理",
    "company.status.suspended": "已暂停",
    "company.status.archived": "已归档",
    "company.access.noEmail": "无可用邮箱",
    "company.access.pendingCount": "{count} 个待处理",
    "company.access.pendingHumanJoins": "待处理人类成员加入",
    "company.access.pendingHumanJoinsDescription": "在其成为活跃公司成员前审核人类成员加入请求。",
    "company.access.removedAssignments": "已清理 {count} 个已分配问题。",
    "company.access.selectCompany": "选择公司以管理访问。",
    "company.access.submittedAt": "提交于 {time}",
    "company.access.unauthorized": "你没有权限管理公司成员。",
    "company.access.unknownRequester": "未知人类请求者",
    "pathDialog.title": "手动指定路径",
    "pathDialog.description": "浏览器安全限制会阻止应用通过文件选择器读取完整本地路径。请复制绝对路径并粘贴到输入框。",
    "pathDialog.mac": "macOS（Finder）",
    "pathDialog.mac.step1": "在 Finder 中找到文件夹。",
    "pathDialog.mac.step2": "按住 Option 并右键点击文件夹。",
    "pathDialog.mac.step3": "点击“将 <文件夹名> 拷贝为路径名”。",
    "pathDialog.windows": "Windows（文件资源管理器）",
    "pathDialog.windows.step1": "在文件资源管理器中找到文件夹。",
    "pathDialog.windows.step2": "按住 Shift 并右键点击文件夹。",
    "pathDialog.windows.step3": "点击“复制为路径”。",
    "pathDialog.stepPaste": "把结果粘贴到路径输入框。",
    "pathDialog.terminal": "终端兜底方式（macOS/Linux）",
    "pathDialog.terminal.step1": "运行",
    "pathDialog.terminal.step2": "运行",
    "pathDialog.terminal.step3": "复制输出并粘贴到路径输入框。",
    "pathInstructions.title": "如何获取完整路径",
    "pathInstructions.description": "把绝对路径（例如 {path}）粘贴到输入框。",
    "pathInstructions.mac.step1": "打开 Finder 并进入该文件夹。",
    "pathInstructions.mac.step2": "右键点击（或按住 Control 点击）该文件夹。",
    "pathInstructions.mac.step3": "按住 Option 键，“拷贝”会变成“拷贝为路径名”。",
    "pathInstructions.mac.step4": "点击“拷贝为路径名”，然后粘贴到这里。",
    "pathInstructions.mac.tip": "也可以打开终端，输入 cd，把文件夹拖进终端窗口并回车。然后输入 pwd 查看完整路径。",
    "pathInstructions.windows.step1": "打开文件资源管理器并进入该文件夹。",
    "pathInstructions.windows.step2": "点击顶部地址栏，完整路径会显示出来。",
    "pathInstructions.windows.step3": "复制路径，然后粘贴到这里。",
    "pathInstructions.windows.tip": "也可以按住 Shift 并右键点击文件夹，然后选择“复制为路径”。",
    "pathInstructions.linux.step1": "打开终端并用 cd 进入该目录。",
    "pathInstructions.linux.step2": "运行 pwd 输出完整路径。",
    "pathInstructions.linux.step3": "复制输出并粘贴到这里。",
    "pathInstructions.linux.tip": "多数文件管理器中，Ctrl+L 可以显示地址栏里的完整路径。",
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function detectInitialLanguage(): AppLanguage {
  if (typeof window === "undefined") return "en";
  try {
    const stored = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    if (stored === "en" || stored === "zh") return stored;
  } catch {
    // Ignore storage access failures.
  }
  return window.navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";
}

export function translateText(language: AppLanguage, key: string, values?: TranslationValues): string {
  const template = translations[language][key] ?? translations.en[key] ?? key;
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (match, name) => {
    const value = values[name];
    return value === undefined ? match : String(value);
  });
}

export function translateInline(language: AppLanguage, zh: string, en: string, values?: TranslationValues): string {
  const template = language === "zh" ? zh : en;
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (match, name) => {
    const value = values[name];
    return value === undefined ? match : String(value);
  });
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => detectInitialLanguage());

  const setLanguage = (nextLanguage: AppLanguage) => {
    setLanguageState(nextLanguage);
  };

  useEffect(() => {
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    } catch {
      // Ignore storage access failures.
    }
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguageState((current) => current === "en" ? "zh" : "en"),
    t: (keyOrZh, valuesOrEn, inlineValues) => (
      typeof valuesOrEn === "string"
        ? translateInline(language, keyOrZh, valuesOrEn, inlineValues)
        : translateText(language, keyOrZh, valuesOrEn)
    ),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
